### ISSUE TITLE
Charts not showing

### ISSUE THREAD

**Issue by OliverLSanz** [Bloufire/KrosmagaTracker#1]
I've played a lot of games using the tracker. All its functionality works, except the win-ratio and turns charts.
![image](https://user-images.githubusercontent.com/15345234/30911090-83d9850e-a387-11e7-968b-85dc403fe735.png)

**Comment by Guiver** [comment]
Hello, (first sorry for my English)
You can load ratio and statistics of a God by cliking on its picture on the left.

**Comment by OliverLSanz** [comment]
Worked, thank you! And great work with the tracker :-)
